### ISSUE TITLE
Change the empire script

### ISSUE THREAD

**Issue by tomole444** [cubidalsphere/Rubber-Ducky#1]
How and where do I have to change the path of the Output File exactly ?

**Comment by cubidalsphere** [comment]
I left the link to the empire script as it has been written by them.

The simplest amendment is to start the function, and specify the location of the output in a new line at the bottom of the powersploit. This will look like;

`Get-ChromeDump | Out-File -filepath "C:\l\filename.txt"`

You can amend more aspects of the script to omit history or change it up as you please.

If you have any other issues please raise them

**Comment by tomole444** [comment]
It worked perfectly thanks :)
