### ISSUE TITLE
email.ps1 Error

### ISSUE THREAD

**Issue by tomole444** [cubidalsphere/Rubber-Ducky#2]
Hello 
I get an error when I try to execute your email.ps1 script:
![screenshot 55](https://user-images.githubusercontent.com/36937933/50574220-3c7c6280-0de4-11e9-98af-2f11d3aa0ac1.png)

**Comment by cubidalsphere** [comment]
have you amended your password and email info in the script?

**Comment by tomole444** [comment]
Yes I did that

**Comment by cubidalsphere** [comment]
are you using ( instead of { at line 12 of the script?

**Comment by tomole444** [comment]
No I exactly copied the script ...

**Comment by cubidalsphere** [comment]
i just did a retest and it ran without errors.

Have you changed your settings in your gmail account to allow less secure apps?

can you post your script here with your password and email only removed?

**Comment by cubidalsphere** [comment]
also, just ensure line 17 has the closing }

**Comment by tomole444** [comment]
![screenshot 56](https://user-images.githubusercontent.com/36937933/50591192-8b7ed200-0e8e-11e9-8576-a1844394165c.png)
I have all my files saved in C:\1

**Comment by tomole444** [comment]
I even changed back the folder's name to "l" instead of "1" and I renamed the script to "email.ps1"
![screenshot 58](https://user-images.githubusercontent.com/36937933/50591461-1f04d280-0e90-11e9-98c9-1eb0206c4ca4.png)
I even added back the " at the end but that just gave me one more error than before
![screenshot 57](https://user-images.githubusercontent.com/36937933/50591400-b7e71e00-0e8f-11e9-8e69-cd9544162dda.png)

**Comment by tomole444** [comment]
I did try to delete the read out messages:
![screenshot 59](https://user-images.githubusercontent.com/36937933/50591621-f6310d00-0e90-11e9-9228-36dabe08b8df.png)

**Comment by tomole444** [comment]
OK I think I got it now! 
My dump PC didn't got the "-" you wrote, so I replaced it with a "-" again then it worked:
![screenshot 60](https://user-images.githubusercontent.com/36937933/50592055-c71b9b00-0e92-11e9-8a8d-7b55caa861c1.png)
sorry for wasting you time

**Comment by cubidalsphere** [comment]
Got there in the end, that’s all that matters
